### ISSUE TITLE
crash: server rejected transaction - on item equip with custom name

### ISSUE THREAD

**Issue by blockparole** [PrismarineJS/minecraft-data#310]
trying to equip a chestplate with the name: `Chest ➢` using the following code:
```
const chestplate = bot.inventory.findInventoryItem(idChestplateDiamond, null);
  if (chestplate) {
    bot.equip(chestplate, 'torso');
  }
```
results in a crash when connected to a server running waterfall and paper for 1.12.2.
the server is also running viaversion.

```
C:\Users\_\IdeaProjects\jscrapbot\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

Error: Server rejected transaction.
    at Bot.<anonymous> (C:\Users\_\IdeaProjects\jscrapbot\node_modules\mineflayer\lib\plugins\inventory.js:551:12)
    at Object.onceWrapper (events.js:422:26)
    at Bot.emit (events.js:315:20)
    at onRejected (C:\Users\_\IdeaProjects\jscrapbot\node_modules\mineflayer\lib\plugins\inventory.js:507:11)
    at confirmTransaction (C:\Users\_\IdeaProjects\jscrapbot\node_modules\mineflayer\lib\plugins\inventory.js:490:7)
    at Client.<anonymous> (C:\Users\_\IdeaProjects\jscrapbot\node_modules\mineflayer\lib\plugins\inventory.js:594:5)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (C:\Users\_\IdeaProjects\jscrapbot\node_modules\minecraft-protocol\src\client.js:88:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (C:\Users\_\IdeaProjects\jscrapbot\node_modules\readable-stream\lib\_stream_readable.js:298:12)

Process finished with exit code 1
```

**Comment by blockparole** [comment]
nevermind, this seems to be not a bug but wrong inventory handling in my code.
