### ISSUE TITLE
PartialReadError: Read error for undefined

### ISSUE THREAD

**Issue by o0F-0oF** [PrismarineJS/minecraft-data#502]
I am using mineflayer py and when every I join a server I get this error 
```
PartialReadError: Read error for undefined : undefined
    at new ExtendableError (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\utils.js:70:5)
    at Object.readVarInt [as varint] (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\datatypes\utils.js:69:45)
    at eval (eval at compile (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1465:36)
    at Object.packet_entity_destroy (eval at compile (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1470:9)
    at eval (eval at compile (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2109:68)
    at packet (eval at compile (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2158:9)
    at CompiledProtodef.read (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:70:12)
    at e.message (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:111:49)
    at tryCatch (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\utils.js:50:16)
```
then the bot leaves

**Comment by extremeheat** [comment]
You need to specify information like the version and whether this happens on other servers with the same version.

**Comment by nickelpro** [comment]
@rom1504 Could we get a "awaiting feedback" tag? This bug might be valid so I don't want to close but it's a rock until we get version information

**Comment by Usercyk** [comment]
the error from o0F-0oF is on the version 1.18.1
I got the same error on 1.18.2
o0F-0oF opened the same issue here:  https://github.com/PrismarineJS/mineflayer/issues/2398

**Comment by Usercyk** [comment]
my robot:

// mcbot.js
const admin_name = 'admin'
const mineflayer = require('mineflayer')
const bot = mineflayer.createBot({
    username: 'mcbot',
    port: 51777
})

bot.on('chat', (username, message)=>{
    if (username != admin_name) return;
    message=message.split(' ')
    console.log(message)
})


PartialReadError: Read error for undefined : undefined
    at new ExtendableError (d:\vscode\nodejs\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (d:\vscode\nodejs\node_modules\protodef\src\utils.js:70:5)
    at Object.readVarInt [as varint] (d:\vscode\nodejs\node_modules\protodef\src\datatypes\utils.js:69:45)
    at eval (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:293:63)
    at Object.command_node (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:303:9)
    at eval (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:837:42)
    at Object.packet_declare_commands (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:842:9)
    at eval (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2231:72)
    at packet (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2322:9)
    at CompiledProtodef.read (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:70:12)
[ 'Are', 'you', 'a', 'mc', 'robot?' ]

I don't know why it can still work, but there must be something wrong

**Comment by Usercyk** [comment]
Sometimes I get this, 

PartialReadError: Read error for undefined : Missing characters in string, found size is 528094 expected size was 162739190
    at new ExtendableError (d:\vscode\nodejs\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (d:\vscode\nodejs\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:48:15)
    at eval (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2011:63)
    at eval (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2098:11)
    at Object.packet_declare_recipes (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2103:9)
    at eval (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2304:70)
    at packet (eval at compile (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2322:9)
    at CompiledProtodef.read (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:70:12)
    at e.message (d:\vscode\nodejs\node_modules\protodef\src\compiler.js:111:49)

**Comment by extremeheat** [comment]
Does that happen on a vanilla server?

**Comment by extremeheat** [comment]
Actually those are two different errors. Please make a new issue @usercyk if it happens on a vanilla server. Since we didn't get any more information from op here about what on what version parsing packet_entity_destroy fails we can close this
