### ISSUE TITLE
FileNotFoundError while running example.py using Python.

### ISSUE THREAD

**Issue by Christian-806** [PrismarineJS/minecraft-data#900]
After downloading the python-minecraft-data-master folder and activating the example.py file, there is an error shown below.

`Traceback (most recent call last):
  File "c:/Users/Student/Documents/DataPacks/_helper/python-minecraft-data-master/example.py", line 3, in <module>
    mcd = minecraft_data("1.13")
  File "c:\Users\Student\Documents\DataPacks\_helper\python-minecraft-data-master\minecraft_data\__init__.py", line 12, in __call__
    return type(version, (object,), convert(_dir, version, edition))
  File "c:\Users\Student\Documents\DataPacks\_helper\python-minecraft-data-master\minecraft_data\tools.py", line 7, in convert
    with open(os.path.join(_dir, 'dataPaths.json')) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\Student\\Documents\\DataPacks\\_helper\\python-minecraft-data-master\\minecraft_data\\data/data/dataPaths.json'`

I also tried `pip install minecraft_data` and it did not fix the problem.

**Comment by extremeheat** [comment]
You should post this issue to https://github.com/SpockBotMC/python-minecraft-data

This repo only holds data.
